server:
  port: 56050
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  use-forward-headers: true
  servlet:
    context-path: /

spring:
  application:
    name: mock-service
  main:
    allow-bean-definition-overriding: true
    banner-mode: 'off'
  redis:
    host: 192.168.158.160
    password: yueliminvc@outlook.com
    port: 6379
  rabbitmq:
    # 推荐写上用户名以及端口号, 密码
    host: 192.168.158.160
    username: guest
    password: guest
    port: 5672
  zipkin:
    # ZipKin服务器地址
    baseUrl: http://192.168.158.160:9411
    sender:
      # 设置以http方法传输
      type: web
    # 关闭服务发现, 否则Spring Cloud会把zipkin的url当做服务名称
    discovery-client-enabled: false
  sleuth:
    sampler:
      # 全采集
      probability: 1

eureka:
  client:
    service-url:
      # eureka注册中心地址
      defaultZone: http://127.0.0.1:53010/eureka
  instance:
    # 使用ip地址进行注册
    ip-address: 127.0.0.1
    # 偏向ip地址注册
    prefer-ip-address: true

management:
  endpoint:
    health:
      # 开启详细信息 -> 访问 actuator/health
      show-details: always
  endpoints:
    web:
      exposure:
        # 激活所有的端点, 默认只有health和info开启的
        include: '*'
      base-path: /act

# 接口文档是否开启
swagger:
  enable: true

notify-url: http://127.0.0.1:56040/order/notify
openProxy: 0
