server:
  port: 56060
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  use-forward-headers: true
  servlet:
    context-path: /

spring:
  application:
    name: web-service
  main:
    allow-bean-definition-overriding: true
    banner-mode: 'off'
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.158.160:3306/recharge_order_trade?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: yueliminvc@outlook.com
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          slow-sql-millis: 1
          log-slow-sql: true
      filters: config,stat,wall,log4j2
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.css,*.ioc,/druid/*"
        session-stat-enable: false
        session-stat-max-count: 1000
        principal-cookie-name: admin
        principal-session-name: admin
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # 白名单
        allow: 127.0.0.1
        # 黑名单
        deny: 192.168.158.1
        reset-enable: false
        login-password: admin
        login-username: admin
      aop-patterns: com.recharge.*.service.*
  rabbitmq:
    # 推荐写上用户名以及端口号, 密码
    host: 192.168.158.160
    username: guest
    password: guest
  thymeleaf:
    cache: false
    check-template-location: true
    servlet:
      content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/static/
    suffix: .html
  zipkin:
    # ZipKin服务器地址
    baseUrl: http://192.168.158.160:9411
    sender:
      # 设置以http方法传输
      type: web
    # 关闭服务发现, 否则Spring Cloud会把zipkin的url当做服务名称
    discovery-client-enabled: false
  sleuth:
    sampler:
      # 全采集
      probability: 1

# rocket mq
rocketmq:
  name-server: 192.168.158.160:9876
  producer:
    group: my-group

# MybatisPlus
mybatis-plus:
  configuration:
    cache-enabled: false
    # 驼峰转换
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      id-type: auto
  # 扫描实体类
  type-aliases-package: com.recharge.*.entity
  # 扫描自定义SQL
  mapper-locations: classpath:com/recharge/*/mapper/*.xml

# 接口文档是否开启
swagger:
  enable: true

# eureka客户端配置
eureka:
  client:
    service-url:
      # eureka注册中心地址
      defaultZone: http://127.0.0.1:53010/eureka
  instance:
    # 使用ip地址进行注册
    ip-address: 127.0.0.1
    # 偏向ip地址注册
    prefer-ip-address: true

# 健康检查
management:
  endpoint:
    health:
      # 开启详细信息 -> 访问 actuator/health
      show-details: always
  endpoints:
    web:
      exposure:
        # 激活所有的端点, 默认只有health和info开启的
        include: '*'
      base-path: /act
